kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pacman
spec:
  path: /
  to:
    kind: Service
    name: pacman-ocp
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

