kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  labels:
    name: mongo
    app.openshift.io/runtime: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1536Mi
            requests:
              cpu: 50m
              memory: 256Mi
          name: mongo
          # env:
          #   - name: MONGO_INITDB_ROOT_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongodb-users-secret
          #         key: database-admin-user
          #   - name: MONGO_INITDB_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongodb-users-secret
          #         key: database-admin-password
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-db
              mountPath: /data/db
          image: mongo
