kind: Service
apiVersion: v1
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    name: mongo
  type: ClusterIP
 
